# Site settings
title: Hannah Zabarsky
description: Hi, I'm Hannah! Welcome to my site!
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hannahzabarsky.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hannah Zabarsky
# user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff. Visit my blog here <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: software engineer + student
email: hello@hannahzabarsky.com
twitter_username: hzabarsky
github_username:  hannah
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
